"""init

Revision ID: 18b0f21d98b4
Revises: 
Create Date: 2025-10-29 23:50:35.819532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b0f21d98b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # This is an initial migration for the existing game.db schema
    # All tables were created via scripts/init_db.py
    # This migration file serves as a baseline for future schema changes
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
